---
master:
    default: rabbitMQ
    rabbitMQ:
        driver: RabbitMQ
        options:
            server: SERVER URL
            port: 5672
            user: USER
            password: PASSWORD
...
