---
queues:
  # test:
  #   driver: Rabbit
  #   options:
  #     host: 172.17.0.1
  #     port: 5672
  #     username: genee
  #     password: 83719730
  #     queue:
  #       name: router
  #     exchange:
  #       name: msgs
...
